### ISSUE TITLE
how were the m1-1m.random constructed?

### ISSUE THREAD

**Issue by remember00000** [RUCAIBox/LLMRank#1]
hello, I try to search some user with items from m1-1m.random in file m1-1m.inter, but I cannot find the corresponding one?does this file include random negative pairs?

**Comment by remember00000** [comment]
同时我查看了random中和原始数据中重合数量，也就是ground truth的数量，发现位置和数量并没有规律或者一致性，想咨询这块的作用和构造方式，谢谢🙏

**Comment by hyp1231** [comment]
Hi, thanks for your attention! The items stored in `ml-1m.random` are randomly selected candidate item IDs, or in other words, negative instances. These candidate item IDs will be fused with ground truth items further in [Trainer](https://github.com/RUCAIBox/LLMRank/blob/master/llmrank/trainer.py). The code to produce this file has been uploaded, and how this file is used has been described in [[data preparation]](https://github.com/RUCAIBox/LLMRank/blob/master/llmrank/dataset/data-preparation.md). Please feel free to leave comments if you have any questions.

您好，感谢关注！`ml-1m.random`中存储的商品 ID 是随机选择的，它们会被看成负样本。这些候选商品会在 [Trainer](https://github.com/RUCAIBox/LLMRank/blob/master/llmrank/trainer.py) 中进一步与正样本融合成为完整的候选集，以用于排序。生成该文件的代码已上传，且该文件是如何被使用的已在[[data preparation]](https://github.com/RUCAIBox/LLMRank/blob/master/llmrank/dataset/data-preparation.md)中描述。这个说明可能比较简略，如果有什么没写清楚的地方，欢迎随时在这里留言，谢谢！

**Comment by hyp1231** [comment]
Due to the lack of updates on this issue for a long time, it is temporarily closed. If you have any questions, feel free to reopen it at any time.
