### ISSUE TITLE
关于baseline的评估细节

### ISSUE THREAD

**Issue by Hans2573** [RUCAIBox/LLMRank#11]
据我了解，这个表格中的zero-shot部分，随机抽取200个用户，作为test set，每个用户1个正样本+19个负采样；

我的问题是，baseline中的full这些模型的指标
1. 是否也是随机抽取200个用户？
2. 是否也是在1+19的方式计算出来的？

![image](https://github.com/RUCAIBox/LLMRank/assets/70685549/0891786e-77ab-45a9-8648-7abbe2143dbf)

另外在3.2节中提到："The top-3 best items retrieved by each candidate generation model will be merged into a candidate set containing a total of 21 items." 我想问一下：
3. 每种检索方式检索的3个中，如果有重复是怎么处理的？

感谢回复！

**Comment by hyp1231** [comment]
感谢关注！

1. full 的模型在训练时使用的是全量的训练集和验证集，在测试时是在与其他方法相同的 200 个采样用户上测试（目前的 arXiv 版本是 200 个采样用户，在 ECIR 录用的版本里我们把采样用户的数量扩展到了 6000 个，本周会更新到 arXiv）。
2. 是的，保证所有方法的测试集是相同的。
3. 如果有重复的情况会保留这些重复，对所有参与比较的方法都是这个策略。

**Comment by Hans2573** [comment]
谢谢您的回复！
