### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Hans2573** [RUCAIBox/LLMRank#13]
https://github.com/RUCAIBox/LLMRank/blob/2d2384ff7d44f89ca147b54d99f36e6b8e7948cc/llmrank/trainer.py#L22-L23

您好，这里我有些困惑，有些不确定。
filed可能指的是user 和 item；
field 2 token_id，token_id 是什么？

 user_token 2 id 和 item_token 2 id 这里的id是什么？

这里可能涉及内部id和外部id，item id、token 和真实item的自然语言名字，这三个如何转换？

感谢您的工作，期望得到您的回复。

**Comment by hyp1231** [comment]
您好，感谢关注我们的工作。

这里 `field` 指 feature 的名字，在这里就是 `user_id` 和 `item_id`。`token` 指的就是外部 id，即数据集里存储的字符串形式的用户和商品 id。`id` 是 RecBole 框架的内部 id，即经过 remapping 之后的数字。

所以这里 `dataset.field2token_id` 是一个字典，key 是 `field` 的名字，value 是存储 "`token` 到 `id` 的映射的字典"。所以取出来的 `user_token2id` 就是能把外部的 user id 映射成内部 user id 的字典，`item_token2id` 同理。

**Comment by Hans2573** [comment]
明白了，感谢

**Comment by Hans2573** [comment]
https://github.com/RUCAIBox/LLMRank/blob/2d2384ff7d44f89ca147b54d99f36e6b8e7948cc/llmrank/trainer.py#L52-L62


![image](https://github.com/RUCAIBox/LLMRank/assets/70685549/464c756a-6982-49af-ab03-6619c2e8410a)

再请教一下，这里的iteraction我不太理解，user_id 和 item_id 长度都是100， 是对应位置是一个用户的交互的一个item吗？
这六个字典有什么联系吗？  还是说“item_id”代表的是这个序列要预测的next_item？

另外，再请教一下这里的positive_u, 和 positive_i 是做什么的？  不求甚解，万分感谢！

**Comment by hyp1231** [comment]
嗯嗯 `item_id` 是这个序列要预测的 next_item。`positive_u` 和 `positive_i` 只是为了和 RecBole 的接口对齐，对 sequential recommendation 来说没有什么实际意义。

**Comment by Hans2573** [comment]
非常有帮助！
