### ISSUE TITLE
pretrained_model缺失问题

### ISSUE THREAD

**Issue by Palpitate18** [RUCAIBox/LLMRank#14]
您好！请问对于新加入的数据集，如何获取该数据集关于POP\BPR\GRU4REC\SASREC模型的pretrained_models呢

**Comment by hyp1231** [comment]
可以参考 https://github.com/RUCAIBox/LLMRank/blob/master/scripts/ob3-zero-shot-abilities.md#conventional-methods

其中有训练 pretrained_models 的脚本，类似

```bash
python run_baseline.py -m BPR -d ml-1m
mv xxx.pth pretrained_models/BPR-ml-1m.pth
```

可以把 `ml-1m` 替换成您的新加入数据集。

**Comment by Palpitate18** [comment]
嗷嗷嗷好的，谢谢您
