### ISSUE TITLE
关于异步调用api

### ISSUE THREAD

**Issue by WANGBohaO-jpg** [RUCAIBox/LLMRank#2]
在使用asyncio异步调用api时显示Error communicating with OpenAI，而当使用串行调用api时，即async_dispatch设为False，可以正常返回结果。

**Comment by hyp1231** [comment]
您好，感谢关注！大概率是网络问题。异步调用时没有成功走默认网络代理，可以考虑替换 `llmrank/openai_api.yaml` 中的 `api_base` 为方便直接访问的网址。
